language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build ./WulAiSDK/
  - dotnet build ./WulAiSDK-Sample/
  - dotnet test ./WulAiSDK-Test/

branches:
  only:
    - dev

notifications:
  email: yangjiangtao@laiye.com

