language: csharp
mono: none
dotnet: 2.2
script:
  - dotnet restore
  - dotnet build ./WulAiSDK/
  - dotnet build ./WulAiSDK-Sample/
branches:
  only:
    - dev

notifications:
  email: yangjiangtao@laiye.com

