language: csharp
mono: none
dotnet: 2.1
script:
  - dotnet restore
  - dotnet build ./WulAiSDK/
  - dotnet build ./WulAiSDK-Sample/
  - dotnet test ./WulAiSDK-Tests/
after_success:
  - cd WulAiSDK-Tests/
  - bash <(curl -s https://codecov.io/bash) -c -F unittest
branches:
  only:
    - dev

notifications:
  email: yangjiangtao@laiye.com

