language: csharp
mono: none
dotnet: 2.2
script:
  - dotnet restore
  - dotnet build ./WulAiSDK/
  - dotnet build ./WulAiSDK-Sample/
  - dotnet tool install --global coverlet.console
  - dotnet test ./WulAiSDK-Tests/ /p:CollectCoverage=true /p:CoverletOutput='./' /p:CoverletOutputFormat=opencover
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "coverage.opencover.xml" -t 0ac78c05-6723-4269-abc5-0aed000de523
branches:
  only:
    - dev

notifications:
  email: yangjiangtao@laiye.com

