language: csharp
mono: none
dotnet: 2.2
script:
  - dotnet restore
  - dotnet build ./WulAiSDK/
  - dotnet build ./WulAiSDK-Sample/
  - dotnet tool install --global coverlet.console
  - cd ./WulAiSDK-Tests
  - dotnet test /p:CollectCoverage=true /p:CoverletOutput='./' /p:CoverletOutputFormat=opencover
  - ls
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ls
  - cd ..
  - ls
  - ./codecov -f "./WulAiSDK-Tests/coverage.opencover.xml" -t 0ac78c05-6723-4269-abc5-0aed000de523
branches:
  only:
    - dev

notifications:
  email: yangjiangtao@laiye.com

