image:
  - Visual Studio 2017
  - Visual Studio 2019
branches:
  only:
    - dev
install:
  - cmd: dotnet tool install --global coverlet.console

test_script:
  - cd ./WulAiSDK-Tests
  - dotnet test /p:CollectCoverage=true /p:CoverletOutput='./' /p:CoverletOutputFormat=opencover
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "coverage.opencover.xml" -t 0ac78c05-6723-4269-abc5-0aed000de523