image: Visual Studio 2019

install:
  # Install Proxy
  - npm install o_o -g
  - cmd: dotnet --version
  - cmd: dotnet tool install --global altcover.visualizer
  - cmd: cd WulAiSDK-Tests/ && dotnet add package AltCover && cd ../
build_script:
  - cmd: dotnet restore WulAiSDK.sln
  - cmd: dotnet build WulAiSDK.sln
test_script:
  # Start Proxy
  - ps: Start-Process -FilePath o_o -NoNewWindow
  # Dotnet Test
  - dotnet build WulAiSDK.sln
  - dotnet test WulAiSDK-Tests /p:AltCover=true
on_finish:
  - cmd: cd WulAiSDK-Tests
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH