image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
- choco install dotnetcore-sdk

build:
  project: WulAiSDK.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\WulAiSDK-Tests\bin\Debug\netcoreapp2.1\WulAiSDK-Tests.dll -noshadow" -filter:"+[WulAiSDK*]* -[WulAiSDK-Tests*]*" -output:".\WulAiSDK_coverage.xml"
- codecov -f "WulAiSDK_coverage.xml"